### PR TITLE
Instantiate constants lazily so unused constants are not instantiated.

### PR DESCRIPTION
**Pull request by exoego**
From my observation on Scala.js-generated JS files, 

- normal `val` in `object` are instantiated if the object is referenced, even if the `val`s are not used in user-land.
- `lazy val` are initialized with dummy value and then lazy-initialization code is generetated in JS. If `lazy val` is not referenced in user-land, such lazy-initialization will get swiped away.

So I think making constants `lazy` will reduce generated JS size.
Ofcourse lazy-initialization will put a small overhead, but not so serious I assume.

In this PR, non-primitive constants are marked as `lazy`,
hoping unused Classes and their instances will not be included in generated JS.
Primitive constants (e.g. `Int` or `String`) are not marked to avoid lazy-initialization overhead, since their involvement may not increase JS size so much.

### CODE REVIEW

**Comment by cquiroz** [comment]
Thanks for this, great work
Did you quanitfy the improvement on size? I have done a few rounds of these and noted that the improvement is not always as I expected so I run them through a test project that uses scala-java-time

**Comment by exoego** [comment]
I experimented on my company project using this branch.
Unfortunately, a fullOptJS-produced file became 2-3% larger (tens of KB) on that project.
The project uses only OffsetDateTime and some constants (predefined instances) of DateFormatter, so I expected some amount of size reduction... but opposite.

I will have more experiment.

**Comment by cquiroz** [comment]
This PR is kind of hard to get now with the latest format changes. Would you like to redo it?

**Comment by exoego** [comment]
Instead of `lazy val`, should we use `def` on constants as same as in PR #158?

**Comment by cquiroz** [comment]
Wow this is a great improvement. I tried with lazy val and didn't see so much improvements, but I didn't apply it so extensively. From my reading of this https://github.com/scala-js/scala-js/issues/2227 I thought switching to def would be beneficial but I can test that later on

Some of my tests switching to def would produce test errors so it has to be tested carefully

**Comment by cquiroz** [comment]
Thanks for this PR

**Pull request merged**
