### PR TITLE
scalajs: set default timezone via js.date

### PR DESCRIPTION
**Pull request by Daxten**

### CODE REVIEW

**Comment by cquiroz** [comment]
This is brilliant. I guess I'd like to add a test

**Comment by Daxten** [comment]
yeah,
also maybe we should put Try around it and let it fail with your original default, since even though toTimeString seems to be stable around all browsers we still presume a lot here. What do you think?

**Comment by cquiroz** [comment]
I was thinking the same though it works in node and it seems you tested in browser
Given that this is a core function erring on the side of safety seems wise

According to spec we should also check if the property `user.timezone` is present and use it

**Comment by Daxten** [comment]
you mean user.timezone as a envrionment variable? do you have an example how that would look like? I will add that case and the error then

**Comment by cquiroz** [comment]
Actually now checking the `user.timezone` case is more complex since it would need to find out the timezone by name to get the offset. I think we can leave that to be done and have what you have done so far only. I doubt it would be very much used

**Comment by cquiroz** [comment]
@Daxten  Do you need a release with this change? Would a snapshot be enough?

**Comment by Daxten** [comment]
I don't need it at the moment, it doesn't block anything for me.. just makes stuff more elegant for the future 👍

**Comment by cquiroz** [comment]
Thanks  a lot for your PR!

**Pull request merged**
