### PR TITLE
Scala 3 Native and cleanup

### PR DESCRIPTION
**Pull request by sideeffffect**
closes https://github.com/cquiroz/scala-java-time/pull/373
closes https://github.com/cquiroz/scala-java-time/pull/364
closes https://github.com/cquiroz/scala-java-time/pull/353
closes https://github.com/cquiroz/scala-java-time/pull/359

blocked on https://github.com/cquiroz/scala-java-locales/pull/342

### CODE REVIEW

**Comment by sideeffffect** [comment]
Hi @lolgab !
```
[warn] Found a call to not defined static method Member(Top(java.time.Month),D9SEPTEMBERL15java.time.MonthEo). Static methods are generated since Scala Native 0.4.3, report this bug in the Scala Native issues. Call defined at file:/home/runner/work/scala-java-time/scala-java-time/tzdb/native/target/scala-2.13/src_managed/main/tzdb/tzdb_java.scala:2698:340
...
[error] Not found Member(Top(java.time.Month),D9SEPTEMBERL15java.time.MonthEo)
[error] 	at /home/runner/work/scala-java-time/scala-java-time/tests/native/target/scala-2.13/src_managed/test/org/threeten/bp/TestMonth.scala:251
...
```
Do you have any idea how to fix these issues? :pray:

**Review by cquiroz — APPROVED** [review]
LGTM, thanks a lot

**Comment by sideeffffect** [comment]
@cquiroz we can merge this! :tada: Please make a new release after that :pray:

**Comment by cquiroz** [comment]
Thanks a lot for getting this through

**Pull request merged**
