### PR TITLE
[WIP] Update Scala & sbt.

### PR DESCRIPTION
**Pull request by exoego**
Release notes
* [Scala 2.12.7](https://github.com/scala/scala/releases/tag/v2.12.7): Faster compilation is remarkable.
* [Scala 2.13.0-M5](https://github.com/scala/scala/releases/tag/v2.13.0-M5)
* [sbt 1.2.3](https://developer.lightbend.com/blog/2018-09-14-sbt-1-2-3/index.html)

### CODE REVIEW

**Comment by cquiroz** [comment]
Thanks a lot, i’m A bit surprised this works as I thought there was no combination of scalajs 1.0.x and scala 2.13.0-M5

**Comment by cquiroz** [comment]
Yeah Travis isn’t building for scalajs 1.0.0-M5 that’s why it works but I bet it will fail if you try to use that’s scalajs version

**Comment by cquiroz** [comment]
Scalatest isn’t available of scala.js 1.0.x we need to either skip tests on 1.0.x or don’t build on Travis with 1.0.x

**Comment by exoego** [comment]
Removed ScalaJS 1.0.x build from Travis, since it has little value if we skipped test.

**Pull request merged**
